name: fuzzy
description: "An all-in-one mobile frontend for multiple image submission sites."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  archive: ^3.6.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  j_util:
    #path: C:/Users/***REMOVED***source/repos/j_util
    #https://dart.dev/tools/pub/dependencies#git-packages
    #git: https://github.com/***REMOVED***/j_util.git
    path: ../j_util/
  oauth2: ^2.0.2
  package_info_plus: ^5.0.1
  path_provider: ^2.1.3
  progressive_image: ^2.0.1
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/
