name: fuzzy
description: "An all-in-one mobile frontend for multiple image submission sites."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  app_links: ^6.1.4
  archive: ^3.6.1
  collection: ^1.18.0
  domain_verification_manager: ^1.0.0
  file_picker: ^8.0.0+1
  file_saver: ^0.2.12
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.2
  flutter_sharing_intent: ^1.1.1
  http: ^1.2.0
  j_util:
    path: ../j_util/
  logging: ^1.2.0
  measure_size: ^4.0.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.3
  progressive_image: ^2.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  string_similarity: ^2.0.0
  url_launcher: ^6.3.0
  video_player: ^2.8.6
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/
