name: fuzzy
description: "An all-in-one mobile frontend for multiple image submission sites."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  app_links: ^6.1.4
  archive: ^3.6.1
  domain_verification_manager: ^1.0.0
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_sharing_intent: ^1.1.1
  http: ^1.2.0
  j_util:
    #path: C:/Users/***REMOVED***source/repos/j_util
    #https://dart.dev/tools/pub/dependencies#git-packages
    # git: 
    #   url: https://github.com/***REMOVED***/j_util.git
    #   version: ^1.0.0
    path: ../j_util/
  logging: ^1.2.0
  measure_size: ^4.0.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.3
  progressive_image: ^2.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  string_similarity: ^2.0.0
  url_launcher: ^6.3.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/
