import 'package:flutter/material.dart';

// const Map<String, Color> htmlColors = {
//   "white": Color(0xFFFFFFFF),
//   "silver": Color(0xFFC0C0C0),
//   "gray": Color(0xFF808080),
//   "black": Color(0xFF000000),
//   "red": Color(0xFFFF0000),
//   "maroon": Color(0xFF800000),
//   "yellow": Color(0xFFFFFF00),
//   "olive": Color(0xFF808000),
//   "lime": Color(0xFF00FF00),
//   "green": Color(0xFF008000),
//   "aqua": Color(0xFF00FFFF),
//   "teal": Color(0xFF008080),
//   "blue": Color(0xFF0000FF),
//   "navy": Color(0xFF000080),
//   "fuchsia": Color(0xFFFF00FF),
//   "purple": Color(0xFF800080),
// };
const Map<String, Color> htmlColorsFull = {
  "mediumvioletred": Color(0xFFC71585),
  "deeppink": Color(0xFFFF1493),
  "palevioletred": Color(0xFFDB7093),
  "hotpink": Color(0xFFFF69B4),
  "lightpink": Color(0xFFFFB6C1),
  "pink": Color(0xFFFFC0CB),
  "darkred": Color(0xFF8B0000),
  "red": Color(0xFFFF0000),
  "firebrick": Color(0xFFB22222),
  "crimson": Color(0xFFDC143C),
  "indianred": Color(0xFFCD5C5C),
  "lightcoral": Color(0xFFF08080),
  "salmon": Color(0xFFFA8072),
  "darksalmon": Color(0xFFE9967A),
  "lightsalmon": Color(0xFFFFA07A),
  "indigo": Color(0xFF4B0082),
  "purple": Color(0xFF800080),
  "darkmagenta": Color(0xFF8B008B),
  "darkviolet": Color(0xFF9400D3),
  "darkslateblue": Color(0xFF483D8B),
  "blueviolet": Color(0xFF8A2BE2),
  "darkorchid": Color(0xFF9932CC),
  "fuchsia": Color(0xFFFF00FF),
  "magenta": Color(0xFFFF00FF),
  "slateblue": Color(0xFF6A5ACD),
  "mediumslateblue": Color(0xFF7B68EE),
  "mediumorchid": Color(0xFFBA55D3),
  "mediumpurple": Color(0xFF9370DB),
  "orchid": Color(0xFFDA70D6),
  "violet": Color(0xFFEE82EE),
  "plum": Color(0xFFDDA0DD),
  "thistle": Color(0xFFD8BFD8),
  "lavender": Color(0xFFE6E6FA),
  "orangered": Color(0xFFFF4500),
  "tomato": Color(0xFFFF6347),
  "darkorange": Color(0xFFFF8C00),
  "coral": Color(0xFFFF7F50),
  "orange": Color(0xFFFFA500),
  "midnightblue": Color(0xFF191970),
  "navy": Color(0xFF000080),
  "darkblue": Color(0xFF00008B),
  "mediumblue": Color(0xFF0000CD),
  "blue": Color(0xFF0000FF),
  "royalblue": Color(0xFF4169E1),
  "steelblue": Color(0xFF4682B4),
  "dodgerblue": Color(0xFF1E90FF),
  "deepskyblue": Color(0xFF00BFFF),
  "cornflowerblue": Color(0xFF6495ED),
  "skyblue": Color(0xFF87CEEB),
  "lightskyblue": Color(0xFF87CEFA),
  "lightsteelblue": Color(0xFFB0C4DE),
  "lightblue": Color(0xFFADD8E6),
  "powderblue": Color(0xFFB0E0E6),
  "darkkhaki": Color(0xFFBDB76B),
  "gold": Color(0xFFFFD700),
  "khaki": Color(0xFFF0E68C),
  "peachpuff": Color(0xFFFFDAB9),
  "yellow": Color(0xFFFFFF00),
  "palegoldenrod": Color(0xFFEEE8AA),
  "moccasin": Color(0xFFFFE4B5),
  "papayawhip": Color(0xFFFFEFD5),
  "lightgoldenrodyellow": Color(0xFFFAFAD2),
  "lemonchiffon": Color(0xFFFFFACD),
  "lightyellow": Color(0xFFFFFFE0),
  "maroon": Color(0xFF800000),
  "brown": Color(0xFFA52A2A),
  "saddlebrown": Color(0xFF8B4513),
  "sienna": Color(0xFFA0522D),
  "chocolate": Color(0xFFD2691E),
  "darkgoldenrod": Color(0xFFB8860B),
  "peru": Color(0xFFCD853F),
  "rosybrown": Color(0xFFBC8F8F),
  "goldenrod": Color(0xFFDAA520),
  "sandybrown": Color(0xFFF4A460),
  "tan": Color(0xFFD2B48C),
  "burlywood": Color(0xFFDEB887),
  "wheat": Color(0xFFF5DEB3),
  "navajowhite": Color(0xFFFFDEAD),
  "bisque": Color(0xFFFFE4C4),
  "blanchedalmond": Color(0xFFFFEBCD),
  "cornsilk": Color(0xFFFFF8DC),
  "teal": Color(0xFF008080),
  "darkcyan": Color(0xFF008B8B),
  "lightseagreen": Color(0xFF20B2AA),
  "cadetblue": Color(0xFF5F9EA0),
  "darkturquoise": Color(0xFF00CED1),
  "mediumturquoise": Color(0xFF48D1CC),
  "turquoise": Color(0xFF40E0D0),
  "aqua": Color(0xFF00FFFF),
  "cyan": Color(0xFF00FFFF),
  "aquamarine": Color(0xFF7FFFD4),
  "paleturquoise": Color(0xFFAFEEEE),
  "lightcyan": Color(0xFFE0FFFF),
  "darkgreen": Color(0xFF006400),
  "green": Color(0xFF008000),
  "darkolivegreen": Color(0xFF556B2F),
  "forestgreen": Color(0xFF228B22),
  "seagreen": Color(0xFF2E8B57),
  "olive": Color(0xFF808000),
  "olivedrab": Color(0xFF6B8E23),
  "mediumseagreen": Color(0xFF3CB371),
  "limegreen": Color(0xFF32CD32),
  "lime": Color(0xFF00FF00),
  "springgreen": Color(0xFF00FF7F),
  "mediumspringgreen": Color(0xFF00FA9A),
  "darkseagreen": Color(0xFF8FBC8F),
  "mediumaquamarine": Color(0xFF66CDAA),
  "yellowgreen": Color(0xFF9ACD32),
  "lawngreen": Color(0xFF7CFC00),
  "chartreuse": Color(0xFF7FFF00),
  "lightgreen": Color(0xFF90EE90),
  "greenyellow": Color(0xFFADFF2F),
  "palegreen": Color(0xFF98FB98),
  "mistyrose": Color(0xFFFFE4E1),
  "antiquewhite": Color(0xFFFAEBD7),
  "linen": Color(0xFFFAF0E6),
  "beige": Color(0xFFF5F5DC),
  "whitesmoke": Color(0xFFF5F5F5),
  "lavenderblush": Color(0xFFFFF0F5),
  "oldlace": Color(0xFFFDF5E6),
  "aliceblue": Color(0xFFF0F8FF),
  "seashell": Color(0xFFFFF5EE),
  "ghostwhite": Color(0xFFF8F8FF),
  "honeydew": Color(0xFFF0FFF0),
  "floralwhite": Color(0xFFFFFAF0),
  "azure": Color(0xFFF0FFFF),
  "mintcream": Color(0xFFF5FFFA),
  "snow": Color(0xFFFFFAFA),
  "ivory": Color(0xFFFFFFF0),
  "white": Color(0xFFFFFFFF),
  "black": Color(0xFF000000),
  "darkslategray": Color(0xFF2F4F4F),
  "dimgray": Color(0xFF696969),
  "slategray": Color(0xFF708090),
  "gray": Color(0xFF808080),
  "lightslategray": Color(0xFF778899),
  "darkgray": Color(0xFFA9A9A9),
  "silver": Color(0xFFC0C0C0),
  "lightgray": Color(0xFFD3D3D3),
  "gainsboro": Color(0xFFDCDCDC),
};
const maroon = Color(0xFF800000);
const sienna = Color(0xFFA0522D);
const wheat = Color(0xFFF5DEB3);
const htmlColorsFullMatcher =
    "mediumvioletred|deeppink|palevioletred|hotpink|lightpink|pink|darkred|red|firebrick|crimson|indianred|lightcoral|salmon|darksalmon|lightsalmon|indigo|purple|darkmagenta|darkviolet|darkslateblue|blueviolet|darkorchid|fuchsia|magenta|slateblue|mediumslateblue|mediumorchid|mediumpurple|orchid|violet|plum|thistle|lavender|orangered|tomato|darkorange|coral|orange|midnightblue|navy|darkblue|mediumblue|blue|royalblue|steelblue|dodgerblue|deepskyblue|cornflowerblue|skyblue|lightskyblue|lightsteelblue|lightblue|powderblue|darkkhaki|gold|khaki|peachpuff|yellow|palegoldenrod|moccasin|papayawhip|lightgoldenrodyellow|lemonchiffon|lightyellow|maroon|brown|saddlebrown|sienna|chocolate|darkgoldenrod|peru|rosybrown|goldenrod|sandybrown|tan|burlywood|wheat|navajowhite|bisque|blanchedalmond|cornsilk|teal|darkcyan|lightseagreen|cadetblue|darkturquoise|mediumturquoise|turquoise|aqua|cyan|aquamarine|paleturquoise|lightcyan|darkgreen|green|darkolivegreen|forestgreen|seagreen|olive|olivedrab|mediumseagreen|limegreen|lime|springgreen|mediumspringgreen|darkseagreen|mediumaquamarine|yellowgreen|lawngreen|chartreuse|lightgreen|greenyellow|palegreen|mistyrose|antiquewhite|linen|beige|whitesmoke|lavenderblush|oldlace|aliceblue|seashell|ghostwhite|honeydew|floralwhite|azure|mintcream|snow|ivory|white|black|darkslategray|dimgray|slategray|gray|lightslategray|darkgray|silver|lightgray|gainsboro";
